version: '3'

services:
  api:
    build: .
    environment:
      DB_USER: postgres
      DB_PASSWORD: bgsnqkik2004
      DB_NAME: local_sntst_v4
      DB_HOST: db
    ports:
      - 7000:7000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: bgsnqkik2004
      POSTGRES_DB: local_sntst_v4
      ALLOW_IP_RANGE: 0.0.0.0/0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5